# Site settings
title: Blog
description: "Awesome."
baseurl: ""
github: 'http://github.com/caulfield'
url: "http://caulfield.github.io"

sass:
  sass_dir: css

# Build settings
markdown: kramdown
permalink: pretty
